# Generated by Django 4.2.24 on 2025-10-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywares', '0005_alter_reserva_valor_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('Econômico', 'Econômico'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Econômico', max_length=20),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
